### ISSUE TITLE
Make Issues: Marketing Inventory Checklist

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/marketing#33]
### Dependency
An issue to make the template #5

### Overview
We need to make a Marketing Inventory Checklist for each project in order to make sure each project is prepared for marketing their project and the efforts are consistent organization-wide.

### Action Items
 Make an issue for each project using the template

- [ ] 100 Automations
- [ ] 311 Data
- [ ] BallotNav
- [ ] Civic Opportunity Project
- [ ] Civic Tech Index
- [ ] Civic Tech Structure
- [ ] Engage
- [ ] Food Oasis
- [ ] Hackforla.org Website
- [ ] Home Unite Us
- [ ] LA TDM Calculator
- [ ] Lucky Parking
- [ ] Public Tree Map
- [ ] Record Clearance Project
- [ ] Undebate
- [ ] VRMS
- [ ] Write for All
- [ ] Youth Justice Nav

### Resources/Instructions/Templates
