### ISSUE TITLE
Make a Template: Marketing Inventory Checklist

### ISSUE THREAD

**Issue by ellewheeler** [hackforla/marketing#5]
### Overview
We need a template for each project so that the marketing team has a complete list of the items a project could have to assess project status.

### Action Items
- [x] Gather a list of potential items (add below in a comment)
- [ ] Draft an issue template (add below in a comment)
- [ ] Review with M & C Community of Practice team
- [ ] Make template (settings>templates, etc) - must have admin access on the repo 
- [ ] Release the dependency on issue #33 

### Resources/Instructions
[See existing templates](https://github.com/hackforla/marketing/issues/new/choose)

**Comment by ellewheeler** [comment]
Logos
 Social media 
Website  / Demo site 
Project one sheet 
Is their hackforla.org project page up to date 
Website or app analytics 
Press releases written or sent 
Media list 
Marketing assets (other than logo, and including things like memes or messaging) 
SEO (Keyword list)
Slide Deck and Videos
Partners
Bio of key team members for interviews
Blog Posts / Articles / White Papers / Case Studies
Podcasts

**Comment by kcoronel** [comment]
I like where the list is heading

**Comment by ExperimentsInHonesty** [comment]
Made template.  Close issue and reopen if we need to edit.
