### ISSUE TITLE
Marketing Epic: 311 Data

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/marketing#61]
### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04), then add all issue links to a comment on this issue under this heading
   ```
   [Name of project] Team Task board issues
   ```
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 1.05)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
  - [ ] add all relevant issue links to a comment on this issue under this heading
   ```
   Project's repo issues
   ```
- [ ] review with org rep.  
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

### Resources
- 1.01 [List of Project Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 [Replace with PROJECT NAME, Issues tab]

**Comment by ExperimentsInHonesty** [comment]
### 311 Data Team Task issues
- https://github.com/hackforla/marketing/issues/13

**Comment by ExperimentsInHonesty** [comment]
### Project's repo issues
#### [label:"p-feature: marketing materials" ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+label%3A%22p-feature%3A+marketing+materials%22+)
- https://github.com/hackforla/311-data/issues/1745
- https://github.com/hackforla/311-data/issues/1692
- https://github.com/hackforla/311-data/issues/1608
#### [label:"Role: Marketing"](https://github.com/hackforla/311-data/issues?q=is%3Aopen+is%3Aissue+label%3A%22Role%3A+Marketing%22)

**Comment by ExperimentsInHonesty** [comment]
Create : Collect Marketing Assets for... issue use template  here https://github.com/hackforla/marketing/issues/new/choose

**Comment by ryanfchase** [comment]
### 311 Data Team Task issues (as of 10/18/2024)
- https://github.com/hackforla/marketing/issues/13
- https://github.com/hackforla/marketing/issues/77

**Comment by ryanfchase** [comment]
I've moved this to `ready for marketing lead`, but I've noted that I had to manually add the `P: 311 Data` label.

**Comment by ExperimentsInHonesty** [comment]
@ryanfchase I added some more check boxes to the action items in the top section and moved the link references into the top as well under resources 3.01 and 3.02

**Comment by ExperimentsInHonesty** [comment]
@ryanfchase I added some more searches and issues.  Basically, I looked at what all other teams had searched and put together a search list and added the once you didn't have to yours.
