### ISSUE TITLE
Epic: Marketing: CoP: Data Science

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/marketing#63]
### Overview
We need to manage all our marketing issues in one place, so that we can better manage the marketing issues and keep the org rep and marketing CoP involved.
### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04), then add all issue links to a comment on this issue under this heading
   ```
   ### CoP: Data Science Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 1.05)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project's repo issue searches
   ```
  - [ ] for each search you perform, indicate what you searched in the filter bar to get the result (exclude "is:issue is:open") and link it to the URL
  - [ ] put the links relevant to that search under that heading
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

### Resources
- 1.01 [List of Project Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 [CoP: Data Science, Issues tab](https://github.com/hackforla/data-science/issues)
- 1.06 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

**Comment by ExperimentsInHonesty** [comment]
x

**Comment by ExperimentsInHonesty** [comment]
### VRMS repo issue searches

#### [is:issue is:open marketing](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+marketing)
- [ ] 

#### [is:issue is:open media](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+media+)
- [ ] 

#### [is:issue is:open partnership](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+partnership+)
- [ ] 

#### [is:issue is:open video](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+video)
- [ ] 

#### [is:issue is:open social](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+social)
- [ ] 

#### [is:open is:issue label:"P-feature: About"](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aopen+is%3Aissue+label%3A%22P-feature%3A+About%22)
- [ ] 

#### [is:issue is:open about](https://github.com/hackforla/[NAME OF REPO]/issues?page=1&q=is%3Aissue+is%3Aopen+about)
- [ ] 

#### [is:issue is:open one sheet](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+one+sheet)
- [ ] 

#### [is:issue stakeholder](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+stakeholder)
- [ ]
