### ISSUE TITLE
Epic: Marketing: TDM Calculator

### ISSUE THREAD

**Issue by Varun710** [hackforla/marketing#66]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### TDM Calculator Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project or CoP's repo issue searches
   ```
     - [ ] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g., [is:issue marketing ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+marketing))
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [TDM Calculator on marketing repo, issue tab]
- 2.02 [TDM Calculator repo, Issues tab]

**Comment by Varun710** [comment]
### TDM Calculator Team Task issues
- https://github.com/hackforla/marketing/issues/23

**Comment by ExperimentsInHonesty** [comment]
### Project or CoP's repo issue searches

### [is:issue marketing is:closed](https://github.com/hackforla/tdm-calculator/issues?q=is%3Aissue+marketing+is%3Aclosed)
- none relevant

### [is:issue is:closed social](https://github.com/hackforla/tdm-calculator/issues?q=is%3Aissue+is%3Aclosed+social)
- [ ] https://github.com/hackforla/tdm-calculator/issues/992

### [is:issue is:open media](https://github.com/hackforla/tdm-calculator/issues?q=is%3Aissue+is%3Aopen+media)
- [ ] https://github.com/hackforla/tdm-calculator/issues/866

### [is:issue is:open stakeholder](https://github.com/hackforla/tdm-calculator/issues?page=2&q=is%3Aissue+is%3Aopen+stakeholder)
- [ ] https://github.com/hackforla/tdm-calculator/issues/1051
- [ ] https://github.com/hackforla/tdm-calculator/issues/888
- [ ] https://github.com/hackforla/tdm-calculator/issues/315

### [is:issue is:closed video](https://github.com/hackforla/tdm-calculator/issues?page=2&q=is%3Aissue+is%3Aclosed+video)
- [ ] https://github.com/hackforla/tdm-calculator/issues/583

### [is:issue one sheet](https://github.com/hackforla/tdm-calculator/issues?q=is%3Aissue+one+sheet)
- [ ] https://github.com/hackforla/tdm-calculator/issues/1333
- [ ] https://github.com/hackforla/tdm-calculator/issues/1298
- [ ] https://github.com/hackforla/tdm-calculator/issues/743
- [ ] https://github.com/hackforla/tdm-calculator/issues/797
