### ISSUE TITLE
Epic: Marketing: Tech Work Experience

### ISSUE THREAD

**Issue by Sonalika982** [hackforla/marketing#67]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [x] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04).  This instruction is SUPER important, clicking on the label and then coping that link, will make sure you don't end up with a potentially larger list of issues that are irrelevant to what this epic is about.  The filter on the issue page, when you get there, will look like this `is:open label:"P: VRMS"` not `is:open VRMS` 
   - [x] Copy the URL and add it to resource 2.01
   - [x] add all issue links to a comment on this issue under this heading
   ```
   ### TWE Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have.  If you find the issues, please add the links to the Resources section 3
   - [x] Collect Marketing Assets for...
      - [x] if you didn't find this issue for your project, then make the issue using Resource 1.06, and link it to resource 3.02
   - [x] Define Marketing Objectives for...
      - [x] if you didn't find this issue for your project, then make the issue using Resource 1.07, and link it to resource 3.01
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [x] search for marketing issues. See the comment below for your searches https://github.com/hackforla/marketing/issues/67#issuecomment-2424108086
     - [x] put the links relevant to that search under each heading, skip duplicates
   - [x] use each search to find issues that seem like they might have content in them that you need for marketing (it might be part of the story you want to tell of the history of the project or an actual marketing artifact, project logo), include agendas, old and new.
   - [x] review the issues you added, adding a check mark next to each issue and adding anything relevant to a new comment.
- [ ] Review the Define (resource 3.01) and Collect (resource 3.02) issues to see what they already have and what they are looking for
- [ ] Go through all issues in comments below, and try to fill out the Define (resource 3.01) and Collect (resource 3.02) issues.  Leaving comments below if there are other marketing items (in the issues) that would be useful for a marketing person joining the team.
- Share with the Product Management Community of Practice
   - [x] add a label `ready for marketing lead`
   - [x] move to the questions / review column
   - [ ] add to the Product Management CoP agenda for discussion
- [ ] Meet with Org rep

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62
- 1.06 Issue Template [Collect Marketing Assets for](https://github.com/hackforla/marketing/issues/new?assignees=&labels=feature%3A+marketing+inventory+checklist&projects=&template=collect-marketing-assets-for-your-project-or-cop.md&title=Collect+Marketing+Assets+for+%5BINSERT+PROJECT+OR+CoP+NAME%5D)
- 1.07 Issue Template [Define Marketing Objectives for](https://github.com/hackforla/marketing/issues/new?assignees=&labels=documentation%2C+Level%3A+Learning%2C+Skill%3A+Brand+Strategy%2C+Skill%3A+Digital+Marketing%2C+Skill%3A+Media+Strategy&projects=&template=define-marketing-objectives-for-your-project-or-cop.md&title=Define+Marketing+Objectives+for+%5BINSERT+PROJECT+OR+CoP+NAME%5D+project)

#### Links created by working on this issue
- 2.01 [TWE on marketing repo, issue tab](https://github.com/hackforla/marketing/labels/P%3A%20Tech%20Work%20Experience)
- 2.02 [TWE repo, Issues tab](https://github.com/hackforla/internship/issues)

#### Marketing Issues for Project
- 3.01 (https://github.com/hackforla/internship/issues/640)
- 3.02 (https://github.com/hackforla/internship/issues/639)

**Comment by Sonalika982** [comment]
@ExperimentsInHonesty I attempted to create this issue, please check.

**Comment by ExperimentsInHonesty** [comment]
@Sonalika982 the link under 2.02 is not connecting to the issue tab on the internship repo, which is where it's supposed to go, Re-read the parent epic if you need to.  After you do that, try to follow the instructions in this issue.

**Comment by ExperimentsInHonesty** [comment]
### Project or CoP's repo issue searches

#### [is:issue is:open marketing](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+marketing)
- [ ] https://github.com/hackforla/internship/issues/602
- [ ] https://github.com/hackforla/internship/issues/615
- [ ] https://github.com/hackforla/internship/issues/598
- [ ] https://github.com/hackforla/internship/issues/502
- [ ] https://github.com/hackforla/internship/issues/127

#### [is:issue is:open media](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+media+)
- [ ] https://github.com/hackforla/internship/issues/627
- [ ] https://github.com/hackforla/internship/issues/317

#### [is:issue is:open partnership](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+partnership+)
- [ ] https://github.com/hackforla/internship/issues/430
- [ ] https://github.com/hackforla/internship/issues/110

#### [is:issue is:open video](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+video)
- [ ] 

#### [is:issue is:open social](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+social)
- [ ] https://github.com/hackforla/internship/issues/317
- [ ] 

#### [is:open is:issue about](https://github.com/hackforla/internship/issues?q=is%3Aopen+is%3Aissue+about)
- [ ] 

#### [is:issue is:open one sheet](https://github.com/hackforla/internship/issues?q=is%3Aissue+is%3Aopen+one+sheet)
- [ ] 

#### [is:issue stakeholder](https://github.com/hackforla/internship/issues?q=is%3Aissue+stakeholder)
- [ ]

**Comment by Sonalika982** [comment]
> * TWE repo, Issues tab

Hi Bonnie, updated the link. It's now redirecting to the issues page.

**Comment by Sonalika982** [comment]
### TWE Team Task issues
- https://github.com/hackforla/marketing/labels/P%3A%20Tech%20Work%20Experience

**Comment by Sonalika982** [comment]
Questions:
1. Haven't found anything for 'Define Marketing Objectives' and 'Collect Marketing Assets'. Do I need to make new issues?

**Comment by ExperimentsInHonesty** [comment]
@Sonalika982 Please continue working on the issue.

**Comment by Sonalika982** [comment]
Question: Should the issues opened in resource 3.01 and 3.02 be done by marketing team?
