### ISSUE TITLE
Epic: Marketing: Expunge Assist

### ISSUE THREAD

**Issue by mariaweissman** [hackforla/marketing#68]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### Expunge Assist Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project or CoP's repo issue searches
   ```
     - [ ] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g., [is:issue marketing ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+marketing))
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [Expunge Assist](https://github.com/hackforla/expunge-assist/issues)
- 2.02 [Replace with PROJECT or CoP NAME repo, Issues tab]

**Comment by mariaweissman** [comment]
### Expunge Assist Team Task issues
-

**Comment by mariaweissman** [comment]
### Expunge Assist repo issue searches
[Create a social media marketing plan #214](https://github.com/hackforla/expunge-assist/issues/214)

**Comment by mariaweissman** [comment]
#### Marketing
[Create a social media marketing plan #214](https://github.com/hackforla/expunge-assist/issues/214)

**Comment by ExperimentsInHonesty** [comment]
### Project or CoP's repo issue searches
the issues with check marks have marketing content in them

#### [is:issue is:open marketing](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+is%3Aopen+marketing)
- [ ] https://github.com/hackforla/expunge-assist/issues/670
- [ ] https://github.com/hackforla/expunge-assist/issues/602
- [ ] https://github.com/hackforla/expunge-assist/issues/432
- [ ] https://github.com/hackforla/expunge-assist/issues/423
- [ ] https://github.com/hackforla/expunge-assist/issues/379
- [ ] https://github.com/hackforla/expunge-assist/issues/214
- [ ] https://github.com/hackforla/expunge-assist/issues/203

#### [is:issue is:open media](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+is%3Aopen+media)
- [ ] https://github.com/hackforla/expunge-assist/issues/993
- [ ] https://github.com/hackforla/expunge-assist/issues/780
- [ ] https://github.com/hackforla/expunge-assist/issues/409
- [ ] https://github.com/hackforla/expunge-assist/issues/214 - duplicate
- [ ] https://github.com/hackforla/expunge-assist/issues/203 - duplicate

#### [is:issue is:open partnership](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+is%3Aopen+partnership)
- [ ] https://github.com/hackforla/expunge-assist/issues/1155
- [ ] plus agendas (see searches above)


#### [is:issue social](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+social)
- [ ] https://github.com/hackforla/expunge-assist/issues/993 (duplicate)
- [ ] https://github.com/hackforla/expunge-assist/issues/780 (duplicate)
- [ ] https://github.com/hackforla/expunge-assist/issues/868
- [ ] https://github.com/hackforla/expunge-assist/issues/215
- [ ] https://github.com/hackforla/expunge-assist/issues/203 (duplicate)
- [ ] https://github.com/hackforla/expunge-assist/issues/109
- [ ] https://github.com/hackforla/expunge-assist/issues/2

#### [is:issue stakeholder](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+stakeholder)
- [ ] https://github.com/hackforla/expunge-assist/issues/1386

#### [is:issue video](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+video)
- no issues that are not already mentioned above

#### [is:issue about](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+about)
- [ ] https://github.com/hackforla/expunge-assist/issues/1628
- [ ] https://github.com/hackforla/expunge-assist/issues/1443
- [ ] https://github.com/hackforla/expunge-assist/issues/1367
- [ ] https://github.com/hackforla/expunge-assist/issues/1366
- [ ] https://github.com/hackforla/expunge-assist/issues/1365
- [ ] https://github.com/hackforla/expunge-assist/issues/1056
- [ ] https://github.com/hackforla/expunge-assist/issues/1051
- [ ] https://github.com/hackforla/expunge-assist/issues/1044
- [ ] https://github.com/hackforla/expunge-assist/issues/993
- [ ] https://github.com/hackforla/expunge-assist/issues/965
- [ ] https://github.com/hackforla/expunge-assist/issues/957
- [ ] https://github.com/hackforla/expunge-assist/issues/902
- [ ] https://github.com/hackforla/expunge-assist/issues/868
- [ ] https://github.com/hackforla/expunge-assist/issues/685
- [ ] https://github.com/hackforla/expunge-assist/issues/684
- [ ] https://github.com/hackforla/expunge-assist/issues/676
- [ ] https://github.com/hackforla/expunge-assist/issues/632
- [ ] https://github.com/hackforla/expunge-assist/issues/624
- [ ] https://github.com/hackforla/expunge-assist/issues/617
- [ ] https://github.com/hackforla/expunge-assist/issues/557
- [ ] https://github.com/hackforla/expunge-assist/issues/519
- [ ] https://github.com/hackforla/expunge-assist/issues/376
- [ ] https://github.com/hackforla/expunge-assist/issues/364
- [ ] https://github.com/hackforla/expunge-assist/issues/338
- [ ] https://github.com/hackforla/expunge-assist/issues/248
- [ ] https://github.com/hackforla/expunge-assist/issues/215
- [ ] https://github.com/hackforla/expunge-assist/issues/214
- [ ] https://github.com/hackforla/expunge-assist/issues/203
- [ ] https://github.com/hackforla/expunge-assist/issues/2

#### [is:issue is:open one sheet](https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+is%3Aopen+one+sheet)
- [ ] https://github.com/hackforla/expunge-assist/issues/1173
- [ ] https://github.com/hackforla/expunge-assist/issues/868
- [ ] https://github.com/hackforla/expunge-assist/issues/215
- [ ] https://github.com/hackforla/expunge-assist/issues/204
- [ ] https://github.com/hackforla/expunge-assist/issues/56
- [ ] https://github.com/hackforla/expunge-assist/issues/164

**Comment by mariaweissman** [comment]
From [10/18 PM CoP Meeting](https://github.com/hackforla/product-management/issues/379#issuecomment-2422998854):
**Action Item Expunge Assist**: Determine which issues found in [BW] comment re: searching for media and marketing are relevant marketing tasks
**Action Item Expunge Assist**: Add comments for issues found that are neither asset collection nor define marketing objectives.
