### ISSUE TITLE
Epic: Marketing: PeopleDepot

### ISSUE THREAD

**Issue by shmonks** [hackforla/marketing#69]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### PeopleDepot Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project or CoP's repo issue searches
   ```
     - [ ] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g., [is:issue marketing ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+marketing))
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [PeopleDepot on marketing repo, issue tab]
- 2.02 [PeopleDepot repo, Issues tab](https://github.com/hackforla/peopledepot/issues)

**Comment by shmonks** [comment]
### PeopleDepot Team Task issues
-

**Comment by shmonks** [comment]
Create issues for

- [ ]  Collect Marketing Assets for...
- [ ]  Define Marketing Objectives for...

Use templates here: https://github.com/hackforla/marketing/issues/new/choose

**Comment by shmonks** [comment]
### Project repo issue searches
the issues with check marks have marketing content in them

#### [is:issue is:open marketing](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+is%3Aopen+marketing)
- [ ] https://github.com/hackforla/peopledepot/issues/103

#### [is:issue is:open media](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+is%3Aopen+media+)
- none relevant

#### [is:issue is:open partnership](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+is%3Aopen+partnership+)
- none 

#### [is:issue is:open video](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+is%3Aopen+video)
- none relevant

#### [is:issue is:open social](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+is%3Aopen+social)
- none relevant

#### [is:issue is:open one sheet](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+is%3Aopen+one+sheet)
- [x] https://github.com/hackforla/peopledepot/issues/153
- [x] https://github.com/hackforla/peopledepot/issues/136

#### [is:issue is:open about](https://github.com/hackforla/peopledepot/issues?page=1&q=is%3Aissue+is%3Aopen+about)
- [x] https://github.com/hackforla/peopledepot/issues/139

#### [is:issue stakeholder](https://github.com/hackforla/peopledepot/issues?q=is%3Aissue+stakeholder)
- [ ] https://github.com/hackforla/peopledepot/issues/377
- [ ] https://github.com/hackforla/peopledepot/issues/426

**Comment by ExperimentsInHonesty** [comment]
@shmonks I updated the comment above with some more searches and links to marketing issues.  

I created some new action items in the top of the comment, please review.

**Comment by shmonks** [comment]
Please provide update
1. Progress: 
   - I've added relevant PD issues with comment to https://github.com/hackforla/marketing/issues/78 (aka Resource 3.02 above). 
   - I need to look through https://github.com/hackforla/marketing/issues/79 (aka Resource 3.01 above).
3. Blockers:  None
4. Availability: 2 hours
5. ETA: Next week

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by shmonks** [comment]
Both the following issues now completed:
- #78 
- #79
