### ISSUE TITLE
Epic: Marketing: Guides 

### ISSUE THREAD

**Issue by JesseTheCleric** [hackforla/marketing#73]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### Guides Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project or CoP's repo issue searches
   ```
     - [ ] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g., [is:issue marketing ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+marketing))
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [Replace with PROJECT OR CoP NAME on marketing repo, issue tab]
- 2.02 [Replace with PROJECT or CoP NAME repo, Issues tab]

**Comment by JesseTheCleric** [comment]
### Guides Team Task issues
- https://github.com/hackforla/marketing/issues/52
- https://github.com/hackforla/marketing/issues/8
- https://github.com/hackforla/marketing/issues/64

**Comment by JesseTheCleric** [comment]
###Knowledgebase-content repo issue searches

#### [is:open label:"CoP: Marketing"] (https://github.com/hackforla/knowledgebase-content/labels/CoP%3A%20Marketing)
- https://github.com/hackforla/knowledgebase-content/issues/27
- https://github.com/hackforla/knowledgebase-content/issues/24
- https://github.com/hackforla/knowledgebase-content/issues/71
- https://github.com/hackforla/knowledgebase-content/issues/32
- https://github.com/hackforla/knowledgebase-content/issues/29

**Comment by ExperimentsInHonesty** [comment]
### Guides Team Task issues
- none currently

**Comment by ExperimentsInHonesty** [comment]
### Project or CoP's repo issue searches
the issues with check marks have marketing content in them
#### [is:issue is:open marketing](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+marketing)
- ~https://github.com/hackforla/guides/issues/136~ nothing relevant
- https://github.com/hackforla/guides/issues/64
- https://github.com/hackforla/guides/issues/44

#### [is:issue is:open media](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+media+)
- no additional relevant links

#### [is:issue is:open partnership](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+partnership+)
- no additional relevant links

#### [is:issue is:open video](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+video)
- [x] https://github.com/hackforla/guides/issues/58

#### [is:issue is:open social](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+social)
- [x] https://github.com/hackforla/guides/issues/122

#### [is:issue is:open one sheet](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+one+sheet)
- [x] https://github.com/hackforla/guides/issues/38
- [x] https://github.com/hackforla/guides/issues/8
- [x] https://github.com/hackforla/guides/issues/6

#### [is:issue is:open about](https://github.com/hackforla/guides/issues?q=is%3Aissue+is%3Aopen+about)
- [x] https://github.com/hackforla/guides/issues/79
- [x] https://github.com/hackforla/guides/issues/58
- [x] https://github.com/hackforla/guides/issues/73
- [x] https://github.com/hackforla/guides/issues/65
- [x] https://github.com/hackforla/guides/issues/55

#### [is:issue stakeholder](https://github.com/hackforla/guides/issues?q=is%3Aissue+stakeholder)
- [x] https://github.com/hackforla/guides/issues/82

**Comment by ExperimentsInHonesty** [comment]
Create issues for

- [ ]  Collect Marketing Assets for...
- [ ]  Define Marketing Objectives for...

use templates here https://github.com/hackforla/marketing/issues/new/choose

**Comment by ExperimentsInHonesty** [comment]
@JesseTheCleric I updated the action items at the top of this issue.
