### ISSUE TITLE
Epic: Marketing: Food Oasis

### ISSUE THREAD

**Issue by farahrobleh** [hackforla/marketing#74]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04)
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### Food Oasis Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] search for marketing issues.  They may have a role or feature label for marketing
   ```
   ### Project or CoP's repo issue searches
   ```
     - [ ] put the links relevant to that search under the following heading
       - for each search you perform, indicate what you searched in the filter bar to get the result and link it to the URL (e.g., [is:issue marketing ](https://github.com/hackforla/311-data/issues?q=is%3Aissue+is%3Aopen+marketing))
   ```
   #### [Replace with what you searched for in the Filter bar]
   - 
   ```
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [Replace with PROJECT OR CoP NAME on marketing repo, issue tab]
- 2.02 [Replace with PROJECT or CoP NAME repo, Issues tab]

**Comment by farahrobleh** [comment]
### Food Oasis Team Task issues

- Placeholder

**Comment by farahrobleh** [comment]
### Project's repo issue searches
the issues with check marks have marketing content in them
#### ["marketing"](https://github.com/hackforla/Food-Oasis/issues?q=is%3Aissue+is%3Aopen+marketing)
- [ ] https://github.com/hackforla/food-oasis/issues/2228
- [ ] https://github.com/hackforla/food-oasis/issues/2226
- [ ] https://github.com/hackforla/food-oasis/issues/2211
- [ ] https://github.com/hackforla/food-oasis/issues/2209
- [x] https://github.com/hackforla/food-oasis/issues/2170
- [ ] https://github.com/hackforla/food-oasis/issues/2071
- [x] https://github.com/hackforla/food-oasis/issues/1666
- [ ] https://github.com/hackforla/food-oasis/issues/1638
- [x] https://github.com/hackforla/food-oasis/issues/1620
- [x] https://github.com/hackforla/food-oasis/issues/1506
- [ ] https://github.com/hackforla/food-oasis/issues/1441
- [ ] https://github.com/hackforla/food-oasis/issues/1433 - Partnership
- [x] https://github.com/hackforla/food-oasis/issues/1356
- [ ] https://github.com/hackforla/food-oasis/issues/1341
- [x] https://github.com/hackforla/food-oasis/issues/1667
- [ ] https://github.com/hackforla/food-oasis/issues/703

#### [label:"p-feature: marketing materials" ](https://github.com/hackforla/Food-Oasis/issues?q=is%3Aissue+is%3Aopen+label%3A%22p-feature%3A+media)
- [x] https://github.com/hackforla/food-oasis/issues/1553
- [ ] https://github.com/hackforla/food-oasis/issues/1544
- [ ] https://github.com/hackforla/food-oasis/issues/1525
- [ ] https://github.com/hackforla/food-oasis/issues/1361
- [ ] https://github.com/hackforla/food-oasis/issues/328
- [ ] https://github.com/hackforla/food-oasis/issues/1310
- [x] https://github.com/hackforla/food-oasis/issues/509
- [ ] https://github.com/hackforla/food-oasis/issues/247

#### [label:"Role: Marketing"](https://github.com/hackforla/Food-Oasis/issues?q=is%3Aopen+is%3Aissue+label%3A%22Role%3A+social)
- [ ] https://github.com/hackforla/food-oasis/issues/1531
- [ ] https://github.com/hackforla/food-oasis/issues/1014

#### [is:issue is:open one sheet](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+is%3Aopen+one+sheet)
- [ ] https://github.com/hackforla/food-oasis/issues/1542
- [x] https://github.com/hackforla/food-oasis/issues/1506 (duplicate under marketing search)

#### [is:issue is:closed social](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+is%3Aclosed+social)
- no issues that are not already mentioned above

#### [is:issue media](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+media)
- no issues that are not already mentioned above

#### [is:issue stakeholder](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+stakeholder)
- no issues that are not already mentioned above

#### [is:issue video](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+video)
- [x] https://github.com/hackforla/food-oasis/issues/239

#### [is:issue is:open partnership](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+is%3Aopen+partnership+)
- [x] https://github.com/hackforla/food-oasis/issues/1949
- [ ] https://github.com/hackforla/food-oasis/issues/1540
- [ ] https://github.com/hackforla/food-oasis/issues/1362
- [x] https://github.com/hackforla/food-oasis/issues/1321
- [ ] https://github.com/hackforla/food-oasis/issues/1299
- [ ] https://github.com/hackforla/food-oasis/issues/1296
- [ ] https://github.com/hackforla/food-oasis/issues/1291
- [ ] https://github.com/hackforla/food-oasis/issues/956
- [ ] https://github.com/hackforla/food-oasis/issues/937

#### [is:issue is:open about](https://github.com/hackforla/food-oasis/issues?page=2&q=is%3Aissue+is%3Aopen+about)
- [ ] https://github.com/hackforla/food-oasis/issues/1637
- [x] https://github.com/hackforla/food-oasis/issues/1633
- [ ] https://github.com/hackforla/food-oasis/issues/1616
- [ ] https://github.com/hackforla/food-oasis/issues/1389

**Comment by farahrobleh** [comment]
## Marketing

- https://github.com/hackforla/food-oasis/issues/1554
- https://github.com/hackforla/food-oasis/issues/1553

**Comment by ExperimentsInHonesty** [comment]
@farahrobleh I updated the comment above with issues for various searches.  I tried to leave out the duplicates.

**Comment by farahrobleh** [comment]
> @farahrobleh I updated the comment above with issues for various searches. I tried to leave out the duplicates. Please review the issues and determine which ones have marketing information inside them.

Sounds good Bonnie! Just went through all the issues, and checked the boxes off of which ones specifically align with marketing/the marketing function.
