### ISSUE TITLE
Epic: Marketing: [Name of Project]

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/marketing#80]
### Overview
We need to manage all the marketing issues for our project or CoP, so that the org rep and marketing CoP can find all our relevant issue easily and add new issues that need to be created to this epic

### Action Items
- [ ] Go to the marketing repo labels page and click on the project label that matches this project (resource 1.04).  This instruction is SUPER important, clicking on the label and then coping that link, will make sure you don't end up with a potentially larger list of issues that are irrelevant to what this epic is about.  The filter on the issue page, when you get there, will look like this `is:open label:"P: VRMS"` not `is:open VRMS` 
   - [ ] Copy the URL and add it to resource 2.01
   - [ ] add all issue links to a comment on this issue under this heading
   ```
   ### [Replace NAME OF PROJECT or CoP] Team Task issues
   - 
   ```
- Check the issue titles you found and indicate which of these they have 
   - [ ] Collect Marketing Assets for...
   - [ ] Define Marketing Objectives for...
- Search the project's repo for any marketing issues, add any links you find to another comment
  - [ ] Go to the project repo issue tab (resource 2.02)
  - [ ] copy this search list block to a comment on this issue  
   ```
   ### Project or CoP's repo issue searches
   
   #### [is:issue is:open marketing](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+marketing)
   - [ ] 
   
   #### [is:issue is:open media](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+media+)
   - [ ] 
   
   #### [is:issue is:open partnership](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+partnership+)
   - [ ] 
   
   #### [is:issue is:open video](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+video)
   - [ ] 
   
   #### [is:issue is:open social](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+social)
   - [ ] 
   
   #### [is:open is:issue label:"P-feature: About"](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aopen+is%3Aissue+label%3A%22P-feature%3A+About%22)
   - [ ] 
   
   #### [is:issue is:open about](https://github.com/hackforla/[NAME OF REPO]/issues?page=1&q=is%3Aissue+is%3Aopen+about)
   - [ ] 
   
   #### [is:issue is:open one sheet](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+is%3Aopen+one+sheet)
   - [ ] 
   
   #### [is:issue stakeholder](https://github.com/hackforla/[NAME OF REPO]/issues?q=is%3Aissue+stakeholder)
   - [ ] 
   ```
   - [ ] customize the search URLs by replacing `[NAME OF REPO]` with the name of your repo
   - [ ] use each search to find issues that seem like they might have content in them that you need for marketing (it might be part of the story you want to tell of the history of the project or an actual marketing artifact, project logo), include agendas, old and new.
   - [ ] review the issues you added, adding a check mark next to each issue and adding anything relevant to a new comment.
- [ ] add a label `ready for marketing lead`
- [ ] move to the questions / review column
   - [ ] we will review the issues they are missing (indicated above) and determine if we need to make issues for this project.
- [ ] Once we feel the epic has all the relevant child issue (this might involve making new issue)
   - [ ] Add the epic issue to their project board and cop product management agenda for discussion
- [ ] Review the Define (resource 3.01) and Collect (resource 3.02) issues to see what they already have and what they are looking for
- [ ] Go through all issues in comments below, and try to fill out the Define (resource 3.01) and Collect (resource 3.02) issues.  Leaving comments below if there are other marketing items (in the issues) that would be useful for a marketing person joining the team.
   - [ ] add a label `ready for marketing lead`
   - [ ] move to the questions / review column
- [ ] Meet with Org rep

#### Links provided by this issue
- 1.01 [List of Project or CoP Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
- 1.02 [Marketing Repo, label page](https://github.com/hackforla/marketing/labels)
- 1.03 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
- 1.04 [Marketing Labels page, search "P:"](https://github.com/hackforla/marketing/labels?q=P%3A)
- 1.05 This issue is a subset of: Create project and CoP marketing epics https://github.com/hackforla/marketing/issues/62

#### Links created by working on this issue
- 2.01 [Replace with PROJECT OR CoP NAME on marketing repo, issue tab]
- 2.02 [Replace with PROJECT or CoP NAME repo, Issues tab]

#### Marketing Issues for Project
- 3.01 
- 3.02
